export enum Technology {
  React = "React",
  Ionic = "Ionic",
  TypeScript = "TypeScript",
  Netlify = "Netlify",
  FaunaDB = "FaunaDB",
  Auth0 = "Auth0",
  Plaid = "Plaid",
  Twilio = "Twilio",
  Mailgun = "Mailgun",
  Datadog = "Datadog",
  CRS = "CRS",
  AWSLambda = "AWS Lambda",
  AmazonS3 = "Amazon S3",
  AmazonTranscribe = "Amazon Transcribe",
  Nodejs = "Nodejs",
  FFmpeg = "FFmpeg",
  Bash = "Bash",
  WebVTT = "WebVTT",
  JSON = "JSON",
}
