name: Test and Deploy (jasondavey.io)

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate build info
        run: node scripts/generate-build-info.cjs

      - name: Build website
        run: npm run build

      - name: Start preview server
        run: npm run preview -- --port 8080 &
        
      - name: Wait for server to start
        run: sleep 5
        
      - name: Debug - check what's being served
        run: |
          echo "Checking page content..."
          curl -v http://localhost:8080 > page_content.html
          echo "Page content saved to page_content.html"
          ls -la dist/
          echo "Page title:"
          grep -o '<title>.*</title>' page_content.html || echo "No title found"
          echo "Looking for root div:"
          grep -o '<div id="root".*</div>' page_content.html || echo "No root div found"
      
      - name: Upload HTML content for debugging
        uses: actions/upload-artifact@v4
        with:
          name: page-content
          path: page_content.html
          
      # Increase wait time to ensure React hydration completes
      - name: Wait longer for React hydration
        run: sleep 10
        
      - name: Verify server is responding
        run: curl -v http://localhost:8080 > hydrated_page.html
      
      - name: Upload hydrated page for debugging
        uses: actions/upload-artifact@v4
        with:
          name: hydrated-page
          path: hydrated_page.html
      
      - name: Run Cypress tests locally
        uses: cypress-io/github-action@v6
        with:
          start: false
          config: |
            {
              "baseUrl": "http://localhost:8080",
              "defaultCommandTimeout": 10000,
              "pageLoadTimeout": 30000,
              "retries": 2
            }

      - name: Trigger Production Deploy on Vercel
        if: success()
        run: |
          curl -X POST "${{ secrets.VERCEL_PROD_DEPLOY_HOOK }}"

      - name: Upload screenshots if tests fail
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
