name: Test and Deploy (jasondavey.io)

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate build info
        run: node scripts/generate-build-info.cjs

      - name: Build the website
        run: npm run build

      # We'll let Cypress handle starting the preview server
      
      - name: Run Cypress tests locally
        uses: cypress-io/github-action@v6
        with:
          # Instead of 'start: false', we specify we're using an existing server
          start: npm run preview -- --port 8080
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
          # Kill the server when the tests are done
          command-prefix: 'percy exec -- npx'
          config: |
            {
              "baseUrl": "http://localhost:8080",
              "defaultCommandTimeout": 10000,
              "pageLoadTimeout": 30000,
              "retries": 2
            }

      - name: Trigger Production Deploy on Vercel
        if: success()
        run: |
          curl -X POST "${{ secrets.VERCEL_PROD_DEPLOY_HOOK }}"

      - name: Upload screenshots if tests fail
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
