name: (Production) CI/CD Pipeline with Vercel Preview

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  test_preview_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🛠️ Install Vercel CLI
        run: npm install --global vercel

      - name: 🧪 Wait for Vercel Preview Deployment
        id: vercel
        uses: patrickedqvist/wait-for-vercel-preview@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectId: ${{ secrets.VERCEL_PROJECT_ID }}
          commitSha: ${{ github.sha }}

      - name: 🧪 Run Cypress Against Preview
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=${{ steps.vercel.outputs.url }}
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: ${{ steps.vercel.outputs.url }}

      - name: 🚀 Deploy To Vercel Production (only if tests pass)
        if: success()
        run: |
          curl -X POST "${{ secrets.VERCEL_PROD_DEPLOY_HOOK }}"
