name: (Production) CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel [Production] Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Get Vercel .env
        run: vercel env pull .env --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Deploy To Vercel [Production]
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
