name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate build info
        run: node scripts/generate-build-info.cjs

      - name: Build the website
        run: npm run build

      - name: Start preview server in background
        run: |
          npm run preview -- --port 8080 &
          echo $! > server.pid
          sleep 5

      - name: Check server is running
        run: |
          curl -v http://localhost:8080 > server_check.html
          echo "Content size: $(wc -c < server_check.html) bytes"
          echo "Checking title tag"
          grep -o '<title>.*</title>' server_check.html || echo "No title found"
      
      - name: Upload server check artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-check
          path: server_check.html
      
      - name: Install Cypress
        uses: cypress-io/github-action@v6
        with:
          # Just install Cypress
          runTests: false

      - name: Cypress version
        run: npx cypress --version
      
      - name: Run Cypress tests
        run: |
          npx cypress run --config baseUrl=http://localhost:8080

      - name: Trigger Production Deploy on Vercel
        if: success()
        run: |
          curl -X POST "${{ secrets.VERCEL_PROD_DEPLOY_HOOK }}"

      - name: Kill preview server
        if: always()
        run: kill $(cat server.pid) || true

      - name: Upload screenshots if tests fail
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
